Repository jupyterlab/jupyterlab-latex, pull requests merged in 2024-09, with the labels that each got.

#231 Fix a bug of synctex edit command
  jupyterlab_latex/synctex.py
Labels: bug

#233 Add missing comma
  README.md
Labels: documentation

#234 docs: fix lint error
  README.md
Labels: documentation

#236 [Docs] Improve the repo description and update screenshot
  README.md
  images/show_preview.png
Labels: documentation

#192 UX improvements
  docs/changelog.md
  jupyterlab_latex/build.py
  package.json
  sample.tex
  src/error.tsx
  src/index.ts
  style/icons/bold.svg
  style/icons/center-align.svg
  style/icons/chart-column-solid.svg
  style/icons/italic.svg
  style/icons/left-align.svg
  style/icons/list.svg
  style/icons/olist.svg
  style/icons/right-align.svg
  style/icons/table.svg
  style/icons/underline.svg
  yarn.lock
Labels: enhancement

#235 Make extension compatible with custom drives
  src/index.ts
Labels: enhancement

#237 Use root_dir configuraion
  jupyterlab_latex/__init__.py
  jupyterlab_latex/build.py
  jupyterlab_latex/synctex.py
Labels: enhancement

#239 Add jupyter-collaboration to Binder link
  binder/requirements.txt
Labels: enhancement

#242 Update UX Improvements branch
  .copier-answers.yml
  .eslintignore
  .github/workflows/binder-on-pr.yml
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/enforce-label.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .gitignore
  .prettierignore
  .prettierrc
  .yarnrc.yml
  CHANGELOG.md
  MANIFEST.in
  README.md
  docs/changelog.md
  eslint.config.js
  images/show_preview.png
  jupyterlab_latex/__init__.py
  jupyterlab_latex/_version.py
  jupyterlab_latex/build.py
  jupyterlab_latex/synctex.py
  package.json
  pyproject.toml
  sample.tex
  schema/plugin.json
  setup.cfg
  setup.py
  setupbase.py
  src/error.tsx
  src/index.ts
  src/pagenumber.tsx
  src/pdf.ts
  style/index.css
  tsconfig.json
  yarn.lock
Labels: maintenance

#245 Support Tectonic engine and execute user-customizable command sequence
  README.md
  jupyterlab_latex/build.py
  jupyterlab_latex/config.py
Labels: enhancement

#243 UX improvements
  README.md
  jupyterlab_latex/build.py
  package.json
  sample.tex
  src/error.tsx
  src/index.ts
  style/icons/bold.svg
  style/icons/center-align.svg
  style/icons/chart-column-solid.svg
  style/icons/italic.svg
  style/icons/left-align.svg
  style/icons/list.svg
  style/icons/olist.svg
  style/icons/right-align.svg
  style/icons/table.svg
  style/icons/underline.svg
  yarn.lock
Labels: enhancement
